<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
	</PropertyGroup>

	<PropertyGroup>
		<RootNamespace>Unosquare.FFME</RootNamespace>
		<LangVersion>preview</LangVersion>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
		<WarningsNotAsErrors>$(WarningsNotAsErrors);CS8019</WarningsNotAsErrors>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FFmpeg.AutoGen" Version="8.1.0" />
		<PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" Version="10.0.203">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
